# small parameter config for tests
HOLE = "_?_"
config = {
        "operators": ["group_sum", "mutate_arithmetic", "group_mutate", "join"],
        "filer_op": ["=="],
        "constants": [3000],
        "aggr_func": ["mean", "sum", "count", "max"],
        "mutate_func": ["mean", "sum", "max", "count", "cumsum"],
        "join_predicates": ["(0, 0)", "(1, 0)", "(0, 1)"],
        "mutate_function": ["lambda x, y: x - y",
                            "lambda x, y: x + y",
                            "lambda x, y: x * y",
                            "lambda x, y: x / y",
                            "lambda x: x - (x * 0.1)",
                            "lambda x, y: y / (x - y)",
                            "lambda x: 1"
                            ],
        "permutation_test": False,
        "random_test": False,
        "partial_table": False,
        "partial_trace": False,
        "level_limit": 4,
        "time_limit":600,
        "solution_limit": 5
    }

target_configs = [
    {
        "operators": ["group_sum", "mutate_arithmetic", "group_mutate", "join"],
        "filer_op": ["=="],
        "constants": [3000],
        "aggr_func": ["mean", "sum", "count", "max"],
        "mutate_func": ["mean", "sum", "max", "count", "cumsum"],
        "join_predicates": ["(0, 0)", "(1, 0)", "(0, 1)"],
        "mutate_function": ["lambda x, y: x - y",
                            "lambda x, y: x + y",
                            "lambda x, y: x * y",
                            "lambda x, y: x / y",
                            "lambda x: x - (x * 0.1)",
                            "lambda x, y: y / (x - y)",
                            "lambda x: 1"
                            ],
        "with_analysis": False,
        "permutation_test": False,
        "random_test": False,
        "partial_table": False,
        "partial_trace": False,
        "level_limit": 4,
        "time_limit":600,
        "solution_limit": 1
    },
    {
        "operators": ["group_sum", "mutate_arithmetic", "group_mutate", "join"],
        "filer_op": ["=="],
        "constants": [3000],
        "aggr_func": ["mean", "sum", "count", "max"],
        "mutate_func": ["mean", "sum", "max", "count", "cumsum"],
        "join_predicates": ["(0, 0)", "(1, 0)", "(0, 1)"],
        "mutate_function": ["lambda x, y: x - y",
                            "lambda x, y: x + y",
                            "lambda x, y: x * y",
                            "lambda x, y: x / y",
                            "lambda x: x - (x * 0.1)",
                            "lambda x, y: y / (x - y)",
                            "lambda x: 1"
                            ],
        "with_analysis": True,
        "permutation_test": False,
        "random_test": False,
        "partial_table": False,
        "partial_trace": False,
        "level_limit": 4,
        "time_limit":600,
        "solution_limit": 1
    },
{
        "operators": ["group_sum", "mutate_arithmetic", "group_mutate", "join"],
        "filer_op": ["=="],
        "constants": [3000],
        "aggr_func": ["mean", "sum", "count", "max"],
        "mutate_func": ["mean", "sum", "max", "count", "cumsum"],
        "join_predicates": ["(0, 0)", "(1, 0)", "(0, 1)"],
        "mutate_function": ["lambda x, y: x - y",
                            "lambda x, y: x + y",
                            "lambda x, y: x * y",
                            "lambda x, y: x / y",
                            "lambda x: x - (x * 0.1)",
                            "lambda x, y: y / (x - y)",
                            "lambda x: 1"
                            ],
        "with_analysis": False,
        "permutation_test": False,
        "random_test": False,
        "partial_table": False,
        "partial_trace": False,
        "level_limit": 4,
        "time_limit":600,
        "solution_limit": 5
    },
    {
        "operators": ["group_sum", "mutate_arithmetic", "group_mutate", "join"],
        "filer_op": ["=="],
        "constants": [3000],
        "aggr_func": ["mean", "sum", "count", "max"],
        "mutate_func": ["mean", "sum", "max", "count", "cumsum"],
        "join_predicates": ["(0, 0)", "(1, 0)", "(0, 1)"],
        "mutate_function": ["lambda x, y: x - y",
                            "lambda x, y: x + y",
                            "lambda x, y: x * y",
                            "lambda x, y: x / y",
                            "lambda x: x - (x * 0.1)",
                            "lambda x, y: y / (x - y)",
                            "lambda x: 1"
                            ],
        "with_analysis": True,
        "permutation_test": False,
        "random_test": False,
        "partial_table": False,
        "partial_trace": False,
        "level_limit": 4,
        "time_limit":600,
        "solution_limit": 5
    },
    {
        "operators": ["group_sum", "mutate_arithmetic", "group_mutate", "join"],
        "filer_op": ["=="],
        "constants": [3000],
        "aggr_func": ["mean", "sum", "count", "max"],
        "mutate_func": ["mean", "sum", "max", "count", "cumsum"],
        "join_predicates": ["(0, 0)", "(1, 0)", "(0, 1)"],
        "mutate_function": ["lambda x, y: x - y",
                            "lambda x, y: x + y",
                            "lambda x, y: x * y",
                            "lambda x, y: x / y",
                            "lambda x: x - (x * 0.1)",
                            "lambda x, y: y / (x - y)",
                            "lambda x: 1"
                            ],
        "with_analysis": False,
        "permutation_test": True,
        "random_test": False,
        "partial_table": True,
        "partial_trace": True,
        "level_limit": 4,
        "time_limit":600,
        "solution_limit": 1
    },
    {
        "operators": ["group_sum", "mutate_arithmetic", "group_mutate", "join"],
        "filer_op": ["=="],
        "constants": [3000],
        "aggr_func": ["mean", "sum", "count", "max"],
        "mutate_func": ["mean", "sum", "max", "count", "cumsum"],
        "join_predicates": ["(0, 0)", "(1, 0)", "(0, 1)"],
        "mutate_function": ["lambda x, y: x - y",
                            "lambda x, y: x + y",
                            "lambda x, y: x * y",
                            "lambda x, y: x / y",
                            "lambda x: x - (x * 0.1)",
                            "lambda x, y: y / (x - y)",
                            "lambda x: 1"
                            ],
        "with_analysis": True,
        "permutation_test": True,
        "random_test": False,
        "partial_table": True,
        "partial_trace": True,
        "level_limit": 4,
        "time_limit":600,
        "solution_limit": 1
    },
{
        "operators": ["group_sum", "mutate_arithmetic", "group_mutate", "join"],
        "filer_op": ["=="],
        "constants": [3000],
        "aggr_func": ["mean", "sum", "count", "max"],
        "mutate_func": ["mean", "sum", "max", "count", "cumsum"],
        "join_predicates": ["(0, 0)", "(1, 0)", "(0, 1)"],
        "mutate_function": ["lambda x, y: x - y",
                            "lambda x, y: x + y",
                            "lambda x, y: x * y",
                            "lambda x, y: x / y",
                            "lambda x: x - (x * 0.1)",
                            "lambda x, y: y / (x - y)",
                            "lambda x: 1"
                            ],
        "with_analysis": False,
        "permutation_test": True,
        "random_test": False,
        "partial_table": True,
        "partial_trace": True,
        "level_limit": 4,
        "time_limit":600,
        "solution_limit": 5
    },
    {
        "operators": ["group_sum", "mutate_arithmetic", "group_mutate", "join"],
        "filer_op": ["=="],
        "constants": [3000],
        "aggr_func": ["mean", "sum", "count", "max"],
        "mutate_func": ["mean", "sum", "max", "count", "cumsum"],
        "join_predicates": ["(0, 0)", "(1, 0)", "(0, 1)"],
        "mutate_function": ["lambda x, y: x - y",
                            "lambda x, y: x + y",
                            "lambda x, y: x * y",
                            "lambda x, y: x / y",
                            "lambda x: x - (x * 0.1)",
                            "lambda x, y: y / (x - y)",
                            "lambda x: 1"
                            ],
        "with_analysis": True,
        "permutation_test": True,
        "random_test": False,
        "partial_table": True,
        "partial_trace": True,
        "level_limit": 4,
        "time_limit":600,
        "solution_limit": 5
    },
{
        "operators": ["group_sum", "mutate_arithmetic", "group_mutate", "join"],
        "filer_op": ["=="],
        "constants": [3000],
        "aggr_func": ["mean", "sum", "count", "max"],
        "mutate_func": ["mean", "sum", "max", "count", "cumsum"],
        "join_predicates": ["(0, 0)", "(1, 0)", "(0, 1)"],
        "mutate_function": ["lambda x, y: x - y",
                            "lambda x, y: x + y",
                            "lambda x, y: x * y",
                            "lambda x, y: x / y",
                            "lambda x: x - (x * 0.1)",
                            "lambda x, y: y / (x - y)",
                            "lambda x: 1"
                            ],
        "with_analysis": False,
        "permutation_test": True,
        "random_test": True,
        "partial_table": True,
        "partial_trace": True,
        "level_limit": 4,
        "time_limit":600,
        "solution_limit": 1
    },
    {
        "operators": ["group_sum", "mutate_arithmetic", "group_mutate", "join"],
        "filer_op": ["=="],
        "constants": [3000],
        "aggr_func": ["mean", "sum", "count", "max"],
        "mutate_func": ["mean", "sum", "max", "count", "cumsum"],
        "join_predicates": ["(0, 0)", "(1, 0)", "(0, 1)"],
        "mutate_function": ["lambda x, y: x - y",
                            "lambda x, y: x + y",
                            "lambda x, y: x * y",
                            "lambda x, y: x / y",
                            "lambda x: x - (x * 0.1)",
                            "lambda x, y: y / (x - y)",
                            "lambda x: 1"
                            ],
        "with_analysis": True,
        "permutation_test": True,
        "random_test": True,
        "partial_table": True,
        "partial_trace": True,
        "level_limit": 4,
        "time_limit":600,
        "solution_limit": 1
    },
{
        "operators": ["group_sum", "mutate_arithmetic", "group_mutate", "join"],
        "filer_op": ["=="],
        "constants": [3000],
        "aggr_func": ["mean", "sum", "count", "max"],
        "mutate_func": ["mean", "sum", "max", "count", "cumsum"],
        "join_predicates": ["(0, 0)", "(1, 0)", "(0, 1)"],
        "mutate_function": ["lambda x, y: x - y",
                            "lambda x, y: x + y",
                            "lambda x, y: x * y",
                            "lambda x, y: x / y",
                            "lambda x: x - (x * 0.1)",
                            "lambda x, y: y / (x - y)",
                            "lambda x: 1"
                            ],
        "with_analysis": False,
        "permutation_test": True,
        "random_test": True,
        "partial_table": True,
        "partial_trace": True,
        "level_limit": 4,
        "time_limit":600,
        "solution_limit": 5
    },
    {
        "operators": ["group_sum", "mutate_arithmetic", "group_mutate", "join"],
        "filer_op": ["=="],
        "constants": [3000],
        "aggr_func": ["mean", "sum", "count", "max"],
        "mutate_func": ["mean", "sum", "max", "count", "cumsum"],
        "join_predicates": ["(0, 0)", "(1, 0)", "(0, 1)"],
        "mutate_function": ["lambda x, y: x - y",
                            "lambda x, y: x + y",
                            "lambda x, y: x * y",
                            "lambda x, y: x / y",
                            "lambda x: x - (x * 0.1)",
                            "lambda x, y: y / (x - y)",
                            "lambda x: 1"
                            ],
        "with_analysis": True,
        "permutation_test": True,
        "random_test": True,
        "partial_table": True,
        "partial_trace": True,
        "level_limit": 4,
        "time_limit":600,
        "solution_limit": 5
    }

]
